In [1]:
import torch
from __future__ import print_function

## demo

In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.1821, 0.7785, 0.5872],
        [0.8605, 0.2647, 0.9221],
        [0.0698, 0.3456, 0.8195],
        [0.1355, 0.7510, 0.6010],
        [0.7352, 0.8300, 0.8166]])


In [7]:
y1 = torch.zeros(5,3, dtype=torch.long)
print(y1)  # 构造一个矩阵全为0，而且数据类型是long。

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [15]:
z = torch.tensor([5.5,3])
z1 = z.new_ones(5,3,dtype=torch.double)
print(z,'\n' ,z1)

tensor([5.5000, 3.0000]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [22]:
x= torch.empty(5,3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 9.5510e-39],
        [1.1020e-38, 9.3674e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])


In [25]:
x= torch.tensor([5.5,3])  # 构造一个张量 直接使用数据
print(x)

tensor([5.5000, 3.0000])


In [26]:
#  创建一个tensor基于已经存在的tensor。
x = x.new_ones(5,3,dtype=torch.double)
# new_* methods take in sizes
print(x)
x = torch.randn_like(x,dtype=torch.float)
# override dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-2.3801,  0.9386,  0.4578],
        [-0.5879,  0.6521, -0.6175],
        [-0.3067, -0.1512, -0.0473],
        [ 1.1383, -0.4103, -1.1618],
        [ 1.8791, -0.7606, -0.0700]])


In [27]:
print(x.size())  # 获取它的尺寸信息：
# torch.Size是一个元组，所以它支持左右的元组操作。

torch.Size([5, 3])


## 操作

In [33]:
y = torch.rand(5, 3)
print(y)
print(x + y)
print(torch.add(x,y))
print(y.add_(x))
# 加法：提供一个输出tensor作为参数
result = torch.empty(5, 3)
print(torch.add(x,y,out=result))

tensor([[0.0661, 0.0469, 0.6814],
        [0.0370, 0.8703, 0.3605],
        [0.4094, 0.6533, 0.1181],
        [0.4737, 0.9254, 0.9681],
        [0.8748, 0.6805, 0.3890]])
tensor([[-2.3141,  0.9854,  1.1392],
        [-0.5509,  1.5224, -0.2570],
        [ 0.1026,  0.5021,  0.0708],
        [ 1.6120,  0.5151, -0.1938],
        [ 2.7539, -0.0801,  0.3190]])
tensor([[-2.3141,  0.9854,  1.1392],
        [-0.5509,  1.5224, -0.2570],
        [ 0.1026,  0.5021,  0.0708],
        [ 1.6120,  0.5151, -0.1938],
        [ 2.7539, -0.0801,  0.3190]])
tensor([[-2.3141,  0.9854,  1.1392],
        [-0.5509,  1.5224, -0.2570],
        [ 0.1026,  0.5021,  0.0708],
        [ 1.6120,  0.5151, -0.1938],
        [ 2.7539, -0.0801,  0.3190]])
tensor([[-4.6942,  1.9240,  1.5970],
        [-1.1388,  2.1746, -0.8745],
        [-0.2041,  0.3509,  0.0236],
        [ 2.7503,  0.1048, -1.3556],
        [ 4.6331, -0.8408,  0.2490]])


In [36]:
print(x)
print(x[:,1])  # 取x第二列
print(x)

tensor([[-2.3801,  0.9386,  0.4578],
        [-0.5879,  0.6521, -0.6175],
        [-0.3067, -0.1512, -0.0473],
        [ 1.1383, -0.4103, -1.1618],
        [ 1.8791, -0.7606, -0.0700]])
tensor([ 0.9386,  0.6521, -0.1512, -0.4103, -0.7606])
tensor([[-2.3801,  0.9386,  0.4578],
        [-0.5879,  0.6521, -0.6175],
        [-0.3067, -0.1512, -0.0473],
        [ 1.1383, -0.4103, -1.1618],
        [ 1.8791, -0.7606, -0.0700]])


In [49]:
#改变大小：如果你想改变一个tensor的大小或者形状，你可以使用torch.view：
x = torch.randn(4,4)
print(x)
print(x.size())
y = x.view(16)
z = x.view(-1,8)
print(y)
print(y.size())
print(z)
print(z.size())

tensor([[ 0.2911, -0.3453, -1.1766, -1.2886],
        [-0.3224, -0.2822,  0.8725, -0.1713],
        [ 1.4680,  0.5184, -0.1978, -0.5404],
        [ 0.8219, -0.5826, -0.4954, -0.3840]])
torch.Size([4, 4])
tensor([ 0.2911, -0.3453, -1.1766, -1.2886, -0.3224, -0.2822,  0.8725, -0.1713,
         1.4680,  0.5184, -0.1978, -0.5404,  0.8219, -0.5826, -0.4954, -0.3840])
torch.Size([16])
tensor([[ 0.2911, -0.3453, -1.1766, -1.2886, -0.3224, -0.2822,  0.8725, -0.1713],
        [ 1.4680,  0.5184, -0.1978, -0.5404,  0.8219, -0.5826, -0.4954, -0.3840]])
torch.Size([2, 8])


In [55]:
# 如果你有一个元素tensor，使用.item（）来获得这个value。
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8705])
0.870497465133667
